resources:
  - name: jfrogClientGoRepo
    type: GitRepo
    configuration:
      gitProvider: LeelaGitHub
      path: leela-dev/jfrog-client-go
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: jfrog_goclient_static_analysis
    steps:
      - name: trigger_all
        type: Bash
        configuration:
          inputResources:
            - name: jfrogClientGoRepo
        execution:
          onExecute:
            - echo Hello
            - echo $res_jfrogClientGoRepo_commitSha
      - name: static_code_analysis
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_all
        execution:
          onExecute:
            - echo Gyana is working on it hard...
      - name: go_sec
        type: Bash
        configuration:
          integrations:
            - name: entArt
          inputSteps:
            - name: trigger_all
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: 1.19.3
            - go version
            - go env GOPATH



