resources:
  - name: jfrogClientGoRepo
    type: GitRepo
    configuration:
      gitProvider: LeelaGitHub
      path: leela-dev/jfrog-client-go
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: jfrog_goclient_static_analysis
    steps:
      - name: trigger_all
        type: Bash
        configuration:
          inputResources:
            - name: jfrogClientGoRepo
        execution:
          onExecute:
            - echo Hello
            - echo $res_jfrogClientGoRepo_commitSha
      - name: static_code_analysis
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_all
        execution:
          onExecute:
            - echo Gyana is working on it hard...
      - name: go_sec
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_all
          environmentVariables:
            RESOLVE_REPO: npm-virtual
        execution:
          onStart:
            #This whole section will be replaced by getting task as jfrog/setup-go
            - pushd $res_jfrogClientGoRepo_resourcePath/setup-go
            - jfrog npmc --repo-resolve $RESOLVE_REPO
            - jfrog npm install
            - npm run dist
            - popd
            - task: $res_jfrogClientGoRepo_resourcePath/setup-go
              id: go_setup_task_from_source
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - echo "Step execution"



