resources:
  - name: jfrogClientGo
    type: GitRepo
    configuration:
      gitProvider: LeelaGitHub
      path: leela-dev/jfrog-client-go
      branches:
        include: ^{{gitBranch}}$
      buildOn:
        commit: true
        pullRequestCreate: true

pipelines:
  - name: Frogbot
    steps:
      - name: prepare_for_frogbot_scan
        type: Bash
        configuration:
          inputResources:
            - name: jfrogClientGo
        execution:
          onExecute:
            - add_run_variables repoName=$(echo $res_jfrogClientGo_gitRepoFullName | cut -f2 -d'/')
            - echo $repoName
      - name: Frogbot_Scan
        type: Bash
        configuration:
          inputSteps:
            - name: prepare_for_frogbot_scan
          integrations:
            - name: jfrogPlatform
            - name: LeelaGitHub
          inputResources:
            - name: jfrogClientGo
          environmentVariables:
            JF_URL: $int_jfrogPlatform_url
            JF_ACCESS_TOKEN: $int_jfrogPlatform_accessToken
            JF_GIT_TOKEN: $int_LeelaGitHub_token
            JF_GIT_PROVIDER: "github"
            JF_GIT_API_ENDPOINT: $int_LeelaGitHub_url
            JF_GIT_OWNER: "leela-dev"
            JF_GIT_REPO: $repoName
        execution:
          onExecute:
            - echo $repoName
            - curl -fLg "https://releases.jfrog.io/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh" | sh
            - ./frogbot scan-pull-requests
            - ./frogbot scan-and-fix-repos
            # For Windows runner:
            # - iwr https://releases.jfrog.io/artifactory/frogbot/v2/[RELEASE]/frogbot-windows-amd64/frogbot.exe -OutFile .\frogbot.exe
            # - .\frogbot.exe scan-pull-requests
            # - .\frogbot.exe scan-and-fix-repos



