name: JFrog Client Go Tests
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - "master"

# Ensures that only the latest commit is running for each PR at a time.
# Ignores this rule for push events.
concurrency:
  group: ${{ github.event.pull_request.number || github.sha }}-trigger
  cancel-in-progress: true
jobs:
  trigger-tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      ref: ${{ github.event.pull_request.head.sha || github.ref }}
