name: JFrog Client Go Tests (On Label)
on:
  pull_request_target:
    types: [labeled]
    branches:
      - "master"

# Ensures that only the latest commit is running for each PR at a time.
# Ignores this rule for push events.
concurrency:
  group: ${{ github.event.pull_request.number || github.sha }}-trigger
  cancel-in-progress: true
jobs:
  trigger-tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
